version: '3.7'
services:
  laravel_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: andcode2019
      MYSQL_DATABASE: vitam
      MYSQL_USER: vitam
      MYSQL_PASSWORD: vitam2020
    ports:
      - 33069:3306
    volumes:
      - ./dbs/schemas/:/var/lib/mysql
    networks:
      laravel_prod_net:
        ipv4_address: 173.21.100.10
  laravel_prod:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - .:/var/www/
      - ./public:/var/www/html
    networks:
      laravel_prod_net:
          ipv4_address: 173.21.100.11
    depends_on:
      - laravel_db
volumes:
  vitam_pro:
  dbs:
networks:
  laravel_prod_net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 173.21.100.0/24

